Version: '${project.version}'

Debug: false

# zh-CN zh-TW en
Lang: '?'

# SQL连接参数
Sql: false
Url: 'jdbc:mysql://localhost:3306/{DATABASE}?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'

# 开启点券交易
Point: false

# Collect: false
# Trade: false

# 物品几天后自动下架，请输入正整数，输入-1为关闭限制
LimitTime: 7

# 上架限制，使用物品的lore进行判断
LimitLore: false
LimitLoreList: 私有,vip,绑定

# 上架数量限制
LimitAmount: true
LimitAmountNum: 35
LimitAmountNumVip: 56

# 上架公告
SellBroadcast: true

# 邮箱数量限制
LimitMail: true
LimitMailNum: 50

# 上架最大金额
MaxPrice: 99999999
# 上架税
Tax: true
# 起征点
TaxThreshold: 100000
# 税率，百分比0~1
TaxRate: 0.002

# 零散购买，关闭后玩家只能一次性全买
BuyPartial: true
